# Release Drafter also supports Probot Config, 
# if you want to store your configuration files in a central repository. 
# This allows you to share configurations between projects, 
# and create a organization-wide configuration file 
# by creating a repository named .github with the file .github/release-drafter.yml.
# 
# https://github.com/release-drafter/release-drafter

name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'

# https://github.com/release-drafter/release-drafter#autolabeler
autolabeler:
  - label: 'automation'
    files:
      - '.github/workflows/*.*'
  - label: 'documentation'
    files:
      - '*.md'

# https://github.com/release-drafter/release-drafter#exclude-contributors
exclude-contributors:
  - 'carstingaxion'

# https://github.com/release-drafter/release-drafter#categorize-pull-requests
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

# https://github.com/release-drafter/release-drafter#version-resolver
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES