# Release Drafter also supports Probot Config,
# if you want to store your configuration files in a central repository.
# This allows you to share configurations between projects,
# and create a organization-wide configuration file
# by creating a repository named .github with the file .github/release-drafter.yml.
#
# https://github.com/release-drafter/release-drafter
commitish: main

name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

# https://github.com/release-drafter/release-drafter#autolabeler
autolabeler:
  - label: 'automation'
    files:
      - '.github/workflows/*'
  - label: 'documentation'
    files:
      - '*.md'

# https://github.com/release-drafter/release-drafter#exclude-contributors
# exclude-contributors:
  # - 'carstingaxion'

# https://github.com/release-drafter/release-drafter#categorize-pull-requests
categories:
    - title: 'Security'
      labels:
          - 'security'
    - title: '🚀 Added'
      labels:
          - 'automation'
          - 'documentation'
          - 'feature'
          - 'enhancement'
    # TODO #36 Create 'Deprecated' label or similar
    #- title: 'Deprecated'
    #  labels:
    # TODO #37 Create 'Removed' label or similar
    #- title: 'Removed'
    #  labels:
    - title: '🐛 Fixed'
      labels:
          - 'fix'
          - 'bug'
    - title: 'Dependency Updates & Maintenance'
      labels:
          - 'dependencies'
          - 'maintenance'

change-template: - $TITLE ([#$NUMBER]($URL))
# change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

# https://github.com/release-drafter/release-drafter#version-resolver
version-resolver:
  major:
    labels:
      # TODO #40 Find a label, that triggers 'major' releases
      - 'changelog:removed'
  minor:
    labels:
      - 'automation'
      - 'documentation'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'security'
      - 'fix'
      - 'bug'
      - 'dependencies'
      - 'maintenance'
  default: patch


template: |
  $CHANGES
