name: figuren.theater Organization CS 

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  require-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Require Checklist
        uses: mheap/require-checklist-action@v2
