name: Call a reusable workflow

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: figuren-theater/.github/.github/workflows/ft-push-pull-standards.yml@main
    secrets: inherit # pass all secrets
