name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '13 23 * * *' # Runs at 23:13.
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update the organization-profile README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - name: Pull in meta.figuren.theater/feed
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://meta.figuren.theater/feed/"
          readme_path: "./profile/README.md"
          max_post_count: 3
