name: figuren.theater Organization Standards for push & pull

on:
  workflow_call:
    secrets:
      token:
        required: true


jobs:
  require-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Require Checklist
        uses: mheap/require-checklist-action@v2
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.token }}
          configuration-path: figuren-theater/.github/.github/labeler.yml
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.4.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "250": "Too Large"
            }
